if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0)
        message(FATAL_ERROR "GCC >= 5.0 required - detected ${CMAKE_CXX_COMPILER_VERSION}")
    endif ()
elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    if (CMAKE-CXX_COMPILER_VERSION VERSION_LESS 5.0)
        message(FATAL_ERROR "Clang >= 5.0 required - detected ${CMAKE_CXX_COMPILER_VERSION}")
    endif ()
elseif (MSVC)
    if (MSVC_VERSION VERSION_LESS 1911)
        message(FATAL_ERROR "Visual Studio >= 2017 15.3 (1911) required - detected ${MSVC_VERSION}")
    endif ()
endif ()
