message(STATUS "------------------------ Configuration for Newton Framework ------------------------")
message(STATUS)
message(STATUS "CMake Generator:            ${CMAKE_GENERATOR}")
message(STATUS "Compiler:                   ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "Compiler Version:           ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "Build type:                 ${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_INSTALL_PREFIX:       ${CMAKE_INSTALL_PREFIX}")
message(STATUS "C++ flags (General):        ${CMAKE_CXX_FLAGS}")
message(STATUS "C++ flags (Release):        ${CMAKE_CXX_FLAGS_RELEASE}")
message(STATUS "C++ flags (RelWithDebInfo): ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
message(STATUS "C++ flags (Debug):          ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS)
message(STATUS "NT_BUILD_TESTS:             ${NT_BUILD_TESTS}")
message(STATUS "NT_BUILD_DOCS:              ${NT_BUILD_DOCS}")
message(STATUS "NT_WARNINGS_ARE_ERRORS:     ${NT_WARNINGS_ARE_ERRORS}")
if (DEFINED BUILD_SHARED_LIBS)
    message(STATUS "BUILD_SHARED_LIBS:          ${BUILD_SHARED_LIBS}")
else ()
    message(STATUS "BUILD_SHARED_LIBS:          OFF")
endif ()
message(STATUS)
message(STATUS "NT Major Version:           ${CMAKE_PROJECT_VERSION_MAJOR}")
message(STATUS "NT Minor Version:           ${CMAKE_PROJECT_VERSION_MINOR}")
message(STATUS "NT Patch Version:           ${CMAKE_PROJECT_VERSION_PATCH}")
message(STATUS)
